data:
  title_size: 30
  body_size: 50
  entity_size: 5
  his_size: 50
  vert_num: 17
  subvert_num: 249
  data_format: news
  npratio: 4

info:
  metrics:
  - group_auc
  - mean_mrr
  - ndcg@5;10
  show_step: 100000

model:
  attention_hidden_dim: 200
  word_emb_dim: 300
  vert_emb_dim: 100
  entity_emb_dim: 100
  subvert_emb_dim: 100

  dropout: 0.2
  filter_num: 400
  head_num: 20
  head_dim: 20
  model_type: nrms
  dense_activation: relu

train:
  batch_size: 32
  epochs: 10
  learning_rate: 0.00005
  loss: cross_entropy_loss
  optimizer: adam
  support_quick_scoring: true
